version: "3"
services:
  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: luis-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - PASSWORD=Lu5571967146#
      - SUDO_PASSWORD=Lu557196714657529564#
    volumes:
      - /home/luisced/Vs-CodeServer/CodeServer:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8443:8443
    restart: unless-stopped
    healthcheck:
      test: curl --fail --show-error --silent localhost:8443
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

