version: "3"

networks:
  - codeserver:
      external: true

services:
  
  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: luis-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - PASSWORD=Lu5571967146#
      - SUDO_PASSWORD=Lu557196714657529564#
      - PROXY_DOMAIN=luiscodeserver.dev
    networks:
      - codeserver
    volumes:
      - /home/luisced/Vs-CodeServer/CodeServer:/config
    ports:
      - 8443:8443
    restart: unless-stopped

