version: "3"
services:
  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: luis-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - PROXY_DOMAIN=luiscodeserver.dev
      - HASHED_PASSWORD="$argon2i$v=19$m=4096,t=3,p=1$6MokWbNPuigqwEeJa5Z5vA$1YVuz5Y0J1tsEfbCJR2VES635eezF5JlHi+m69rJe48"
      - SUDO_PASSWROD_HASH="$argon2i$v=19$m=4096,t=3,p=1$bGjPbg9kSUTfINv8MNTmUg$E/Jl5mzqKj4kZDXYqGNWwGl/5jjwI+ohAiksBju11N8"
    volumes:
      - /home/luisced/Vs-CodeServer/CodeServer:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  traefik:
    image: "traefik:v2.5"
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - "433:433"
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
